site_name: ZJU API Docs
site_description: 浙江大学 API 文档

repo_url: https://github.com/eWloYW8/ZJU-API-Docs
repo_name: ZJU API Docs
repo_type: github

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到浅色模式
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.action.edit

nav:
  - 首页: index.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed

