site_name: ZJU API Docs
site_description: 浙江大学 API 文档

repo_url: https://github.com/eWloYW8/ZJU-API-Docs
repo_name: ZJU API Docs
repo_type: github

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - search.suggest
    - content.code.copy
    - content.action.edit

nav:
  - 首页: index.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed

